name: tdr_core
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  apk_installer: ^0.0.4
  # cloud_firestore: ^5.0.1
  connectivity_plus: ^6.0.3
  device_info_plus: ^10.1.0
  dio: ^5.4.3+1
  equatable: ^2.0.5
  # firebase_core: ^3.1.0
  flutter:
    sdk: flutter
  flutter_modular: ^6.3.4
  flutter_secure_storage: ^9.2.2
  geolocator: ^12.0.0
  loading_animation_widget: ^1.2.1
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  result_dart: ^1.1.1
  signals_flutter: ^5.2.2
  top_snackbar_flutter: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

 