name: tdr_core
description: "A new Flutter package project."
version: 1.0.11
homepage:

environment:
  sdk: '>=3.5.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  apk_installer: ^0.0.4
  connectivity_plus: ^6.0.3
  device_info_plus: ^10.1.0
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter_modular: ^6.3.4
  shared_preferences: ^2.3.1
  loading_animation_widget: ^1.2.1
  package_info_plus: ^8.0.2
  path_provider: ^2.1.3
  result_dart: ^1.1.1
  signals_flutter: ^5.2.2
  top_snackbar_flutter: ^3.1.0
  vibration: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

 