name: tdr_core
description: "A new Flutter package project."
version: 1.0.5
homepage:

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  apk_installer: ^0.0.4
  # cloud_firestore: ^5.0.1
  connectivity_plus: ^6.0.3
  device_info_plus: ^10.1.0
  dio: ^5.4.3+1
  equatable: ^2.0.5
  # firebase_core: ^3.1.0
  flutter:
    sdk: flutter
  flutter_modular: ^6.3.4
  shared_preferences: ^2.3.1
  geolocator: ^13.0.1
  loading_animation_widget: ^1.2.1
  package_info_plus: ^8.0.2
  path_provider: ^2.1.3
  result_dart: ^1.1.1
  signals_flutter: ^5.2.2
  top_snackbar_flutter: ^3.1.0
  vibration: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

 